### ISSUE TITLE
ngSanitize dependency

### ISSUE THREAD

**Issue by omailson** [mattlewis92/angular-bootstrap-confirm#1]
This package does not have angular-sanitize as a dependency (only as a devDependency) although it's used in the code. I guess you forgot to remove the requirement for ngSanitize from the module?

**Comment by mattlewis92** [comment]
Angular sanitise is used as the ng-bind-html directive is used in the popover. I've now correctly marked it as a dependency in bower.json and released 0.1.1 which fixes this :)
