### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by antiPoP** [mattlewis92/angular-bootstrap-confirm#11]
I get this error when injecting this module to my app. Please check demo (see console) at http://plnkr.co/edit/kmZGZbEjjXp26HjRf1ej

**Comment by mattlewis92** [comment]
The source code is written using the commonjs module system, unless you're using browserify / webpack you need to include `dist/angular-bootstrap-confirm.js` and not `src/angular-bootstrap-confirm.js`

**Comment by antiPoP** [comment]
I updated the plunker with the source from dist/angular-bootstrap-confirm.min.js . It still fails when loading the module.

http://plnkr.co/edit/kmZGZbEjjXp26HjRf1ej?p=previer

**Comment by antiPoP** [comment]
I got it working, thanks.
