### ISSUE TITLE
Conditional Popup

### ISSUE THREAD

**Issue by rinogueira** [mattlewis92/angular-bootstrap-confirm#14]
Could we have a way to control whether the popup should open or the confirm function be called without popup-confirmation?

It could be done in different ways...
  1. A new attribute "isActive" or "shouldPopup". 
  2. The message could popup only if there is actually a message.

I do prefer the first option, more explicit, and no impact if that flag takes a "true" default.

**Comment by mattlewis92** [comment]
How about `is-disabled` and setting it to true would disable the popup?

**Comment by rinogueira** [comment]
That would be perfect... as long as it fires the confirm function.

**Comment by rinogueira** [comment]
I think it is not calling the onConfirm action.... the idea is to avoid the confirmation popup, but to invoke the method that would be invoked onConfirm.

**Comment by rinogueira** [comment]
OK. It does work the way you pointed.
Thanks.
