### ISSUE TITLE
Warning when using popover - $tooltip is now deprecated. Use $uibTooltip instead.

### ISSUE THREAD

**Issue by skattabrain** [mattlewis92/angular-bootstrap-confirm#15]
When using newer versions of UI Bootstrap (I'm using 0.14.3), creating a popover triggers a warning...

`$tooltip is now deprecated. Use $uibTooltip instead.`

My popover directive looks like...

`<button class="btn btn-danger btn-xs" mwl-confirm data-title="Confirm Deletion" data-message="Are you sure you know what you want to delete this?" data-confirm-text="Delete" data-cancel-text="Cancel" data-placement="left" data-on-confirm="delete()" data-on-cancel="cancelClicked = true" data-confirm-button-type="danger" data-cancel-button-type="default">Delete</button>`

**Comment by mattlewis92** [comment]
I think that's a bug with ui-bootstrap, as this module doesn't even use the `$tooltip` service, only `$position` and there is already a [conditional check](https://github.com/mattlewis92/angular-bootstrap-confirm/blob/master/src/angular-bootstrap-confirm.js#L25) for using the latest prefixed version of the service. I've just updated [the demo](http://mattlewis.me/angular-bootstrap-confirm/) to use the latest ui-bootstrap and there's no deprecation warning there either.

**Comment by skattabrain** [comment]
OK, yeah that was really weird... thanks for the clarification! Happy new year!
