### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by DrowningElysium** [mattlewis92/angular-bootstrap-confirm#17]
Hi, I am using your plugin for the confirmation boxes and they work great in combination with the delete buttons for my ui tree. But I had to put the cancel button inside of the angular component and now I am not able to use: http://mistic100.github.io/Bootstrap-Confirmation/ as a cancel button. Could you maybe tell me how I am able to use your plugin as a cancel button?

The current cancel button looks like this: 
&#60;a href="{{ $previousUrl }}" class="btn btn-danger" data-toggle="confirmation" role="button">@lang('general.cancel')&#60;/a>

We use Laravel for the $previousUrl and @lang is a blade function

**Comment by mattlewis92** [comment]
Sorry I don't quite follow what you mean, can you explain a bit more, maybe with some example code?

**Comment by DrowningElysium** [comment]
At the moment the cancel button works like this: 
<img src="http://i.imgur.com/59WtzDm.png">

When you press yes you are revered back. But when you press no you stay at the page.
How am I able to make this work with your plugin?

**Comment by mattlewis92** [comment]
All the install instructions + API is in the readme: https://github.com/mattlewis92/angular-bootstrap-confirm#installation and there's a working demo you can see the source of: https://github.com/mattlewis92/angular-bootstrap-confirm/blob/master/index.html#L61

If there's something specific you get stuck on then let me know :smile:
