### ISSUE TITLE
Displaying confirm popover

### ISSUE THREAD

**Issue by santosguilherme** [mattlewis92/angular-bootstrap-confirm#18]
The confirm popover always appears when the element is clicked? Is there any way to display it according to a flag?

I put the "mwl-confirm" in the `<tr>` with an "is-open" attribute to false value, and when I click on button in `<tr>`, I change the value of "is-open" for true, but when I click on line, the popover is also displayed and changes the value of the "is-open.

Need:
Show  confirm popover on a `<tr>` when click on button that is within the same `<tr>`.

Are you need the code?

Thanks.

**Comment by mattlewis92** [comment]
Is-open is used for manually opening and closing the popover, you want the is-disabled attribute instead.

**Comment by santosguilherme** [comment]
but the is-disabled also does not work when I click on the element, the popover is opened even with the is-disabled="false"

**Comment by mattlewis92** [comment]
You want `is-disabled="true"` to disable it

**Comment by mattlewis92** [comment]
You want is-disabled=“true” to disable it

**Comment by santosguilherme** [comment]
@mattlewis92 the bug occurs when combines the attribute `is-open` with `is-disabled`.

The popover is opened even with the attribute `is-disabled` is `true`.

Example:
`<div ng-init="vm = {title: 'Are you sure?', message: 'Are you really sure you want to do this?', confirmText: 'Yes', cancelText: 'No', open: false, disabled:true}">`

            <button class="btn btn-default" 
                           mwl-confirm 
                           title="{{ vm.title }}" 
                           message="{{ vm.message }}" 
                           confirm-text="{{ vm.confirmText }}" 
                           cancel-text="{{ vm.cancelText }}" 
                           is-open="vm.open" 
                           is-disabled="vm.disabled"> Target 
              </button>

          <button class="btn btn-default" 
                         ng-click="(vm.disabled = false) || (vm.open = true)"> Open Target
          </button>
`</div>`


The problem is on line 70 of the angular-bootstrap-confirm.js file, because the `vm.IsOpen` variable receives `true` even not satisfying the condition of the line 53.

**Comment by santosguilherme** [comment]
I changed the code for function togglePopover (code below), but the tests broke, is probably the situation with the two attributes (IsOpen and isDisabled) together was not intended.

`function togglePopover() {
      !vm.isDisabled ? angular.noop() : !vm.isVisible ? showPopover() : hidePopover();
      $scope.$apply();
 }`

**Comment by santosguilherme** [comment]
#19
