### ISSUE TITLE
Focus on cancel button

### ISSUE THREAD

**Issue by jacktol** [mattlewis92/angular-bootstrap-confirm#20]
Right now you can only set focus on the confirm button. For destructive operations it would also be nice if the focus could be on the cancel button. 

Do you see this as a feasible feature for angular-bootstrap-confirm?

**Comment by mattlewis92** [comment]
This seems like a reasonable request, should be able to find some time to implement it this weekend 😀

**Comment by jacktol** [comment]
Nice! I'll await your change 👍

**Comment by mattlewis92** [comment]
Released in 2.0.0 😄

**Comment by jacktol** [comment]
Works perfectly, thanks! 👍
