### ISSUE TITLE
Auto-detect position

### ISSUE THREAD

**Issue by Sir-J** [mattlewis92/angular-bootstrap-confirm#23]
How to auto-detect the position of the popover?

**Comment by mattlewis92** [comment]
As the library uses the ui-bootstrap position service under the hood you should be able to use any valid position option that the ui-bootstrap popover provides e.g. `auto top` etc: https://angular-ui.github.io/bootstrap/#/popover

You'll also need to use the latest ui-bootstrap library for this.

**Comment by probaner** [comment]
I am getting an issue. The confirm popover is used on click of href from angular UI grid. Now every time, the popover appears, a fixed offset around 150 px gets added to the 'top' attribute, as a result of which it appears much below than the co-ordinate where I click the href.
