### ISSUE TITLE
Getting Uncaught TypeError: $parse(...).assign is not a function with 2.1.0

### ISSUE THREAD

**Issue by jrgleason** [mattlewis92/angular-bootstrap-confirm#24]
I have the following bower...

```
"dependencies": {
    "angular": "^1.5",
    "angular-animate": "^1.5",
    "angular-aria": "^1.5",
    "angular-material": "^1",
    "angular-route": "^1.5",
    "angular-sanitize": "^1.5",
    "angular-touch": "^1.5",
    "components-font-awesome": "*",
    "restangular": "*",
    "underscore": "*",
    "angular-ui": "*",
    "angular-bootstrap": "0.13.3",
    "angular-ui-router": "*",
    "angular-ui-utils": "*",
    "angular-ui-router-tabs": "1.6.0",
    "angularjs-dropdown-multiselect": "*",
    "angular-bootstrap-confirm": "*",
    "jquery-ui": "*",
    "jquery": "*",
    "moment": "*",
    "d3": "*",
    "waypoints": "3.1.1"

  },
  "overrides": {
    "waypoints": {
      "_comment" : "I had to override because it wasn't including sticky. We should get rid of sticky because we don't really use it but for now this...",
      "main": ["./lib/noframework.waypoints.js", "./lib/shortcuts/sticky.js"]
    }
  },
  "resolutions": {
    "angular": "^1.5"
  },
```

But when I run and try to get the confirm I get...

    Uncaught TypeError: $parse(...).assign is not a function

From 

```
.controller('PopoverConfirmCtrl', ["$scope", "$rootScope", "$element", "$attrs", "$compile", "$document", "$window", "$timeout", "$injector", "$templateRequest", "$parse", "confirmationPopoverDefaults", function($scope, $rootScope, $element, $attrs, $compile, $document, $window, $timeout,
	                                             $injector, $templateRequest, $parse, confirmationPopoverDefaults) {
	    var vm = this;
	    vm.defaults = confirmationPopoverDefaults;
	    vm.$attrs = $attrs;
	    var positionServiceName = $injector.has('$uibPosition') ? '$uibPosition' : '$position';
	    var positionService = $injector.get(positionServiceName);
	    var templateUrl = $attrs.templateUrl || confirmationPopoverDefaults.templateUrl;
	    var popoverScope = $rootScope.$new(true);
	    popoverScope.vm = vm;

	    function assignOuterScopeValue(scopeName, value) {
	      if (angular.isDefined(scopeName)) {
	        $parse(scopeName).assign($scope, value); // Thrown here!
	      }
	    }
```

**Comment by mattlewis92** [comment]
Sounds like you're missing a required attribute, what's your HTML for using the directive?

**Comment by jrgleason** [comment]
Everything seems to work if I comment out 

            function showPopover() {
	      if (!vm.isVisible && !evaluateOuterScopeValue($attrs.isDisabled, false)) {
	        vm.popover.css({display: 'block'});
	        positionPopover();
	        applyFocus();
	        vm.isVisible = true;
	        // assignOuterScopeValue($attrs.isOpen, true);
	      }
	    }

	    function hidePopover() {
	      if (vm.isVisible) {
	        vm.popover.css({display: 'none'});
	        vm.isVisible = false;
	        //assignOuterScopeValue($attrs.isOpen, false);
	      }
	    }

My jade looks like this...

span.btn.btn-claimed.claim-button.alerts-button(
                    ng-switch-when="mine",
                    mwl-confirm,
                    title="{{prop1}}",
                    message="{{prop2}}",
                    placement="{{prop3}}",
                    confirm-text="{{prop4}}",
                    cancel-text="{{prop5}}",
                    on-confirm="doConfirm(alert, 'claim')",
                    on-cancel="cancelClicked = true",
                    confirm-button-type="warning",
                    is-open="false",
                    cancel-button-type="default") {{person}}

I am sure you are correct but this looks like something new after my upgrade(We used 0.3.0 before upgrading to 2.1). It could also be a bad version of ui-bootstrap component.

**Comment by mattlewis92** [comment]
It could be the ng switch, can you reproduce in a Plunker?

**Comment by jrgleason** [comment]
I will work on it, if I downgrade to 1.0.1 I get...

> [$compile:nonassign] Expression 'false' in attribute 'isOpen' used with directive 'mwlConfirm' is non-assignable!

**Comment by mattlewis92** [comment]
Oh it's the is-open="false". Angular is trying to bind a valuable to a Boolean value hence why it's throwing.

**Comment by jrgleason** [comment]
Yeah I got that and it seems to work assigning it to a scope variable but the error message in 2.1.0 is cryptic if that is the same error. Maybe we should try to make this clear like it is in 1.0.1

**Comment by mattlewis92** [comment]
I agree that the error should be more descriptive, I'll try and push a fix tomorrow.
