### ISSUE TITLE
`popover-class` ?

### ISSUE THREAD

**Issue by sgarbesi** [mattlewis92/angular-bootstrap-confirm#25]
Anyway to set the `popover-class` attribute?

**Comment by mattlewis92** [comment]
You have a few options, you could either use a custom template, or if using a language like sass or less then extend the current popover class. I guess you're not using this with bootstrap?

**Comment by sgarbesi** [comment]
I'm using this with Angular UI Bootstrap.

`tooltip-class - Custom class to be applied to the tooltip.`

Works the same for popovers in the framework. Was hoping there was a way to simply add the parental class without a custom template.

**Comment by mattlewis92** [comment]
Ok, it's dead simple to add support for this. I should have the time to work on it tomorrow 🙂

**Comment by mattlewis92** [comment]
Released in 2.3.0 😄
