### ISSUE TITLE
unsafe html support in message 

### ISSUE THREAD

**Issue by SergeyRudakov** [mattlewis92/angular-bootstrap-confirm#26]
Hey Matt,
Can you have an option to include html form elements (like <input>) to the confirm popup? By now they are stripped out from message text because html is not trusted.
I'm using `$sce.trustAsHtml( vm.message);` to allow any html but maybe it can be a good idea to turn on/off unsafe html on directive level.
Thanks,

**Comment by mattlewis92** [comment]
I don't really like the idea of including this option, as I worry someone might use it without understanding the risks involved. 

Also as the directive template uses an isolate scope you wouldn't be able to access the form input values anyway. I feel your problem could be better solved by using the standard UI-bootstrap popover with a custom HTML template, which would share the scope and allow you to access the form contents 😀
