### ISSUE TITLE
Inefficient as action button in column's table

### ISSUE THREAD

**Issue by dzegarra** [mattlewis92/angular-bootstrap-confirm#28]
I used this component for a Delete action button in a column's table and notice a huge performance problem during the first data rendering when the table have several rows (even with 60 rows in an Intel i5 CPU the lag problem is well noticed). The reason is that this component force a new $digest cycle every time a new instance is created (and ng-repeat create several of course). 
A workaround is to use virtual repeat but the problem is still really there.

**Comment by mattlewis92** [comment]
You would have this problem using *any* angular component in a large table, there's not really anything I can do to make this component more performant. 

As you said using a virtual scroll would solve the problem, I've had really good results with this [library](https://github.com/kamilkp/angular-vs-repeat). Sorry there's not much more I can do to help.
