### ISSUE TITLE
Can you provide some input on confirmation like text? so that we can capture feedback of user.

### ISSUE THREAD

**Issue by MrSpark2591** [mattlewis92/angular-bootstrap-confirm#29]

**Comment by mattlewis92** [comment]
I think this kind of functionality is better suited to a standard ui-bootstrap popover: https://angular-ui.github.io/bootstrap/#/popover

**Comment by aurimus** [comment]
This would be useful actually.

**Comment by mattlewis92** [comment]
There's too many possible config options to be able to add this e.g
Should it be a textarea or an input?
Should it be required, have a min / max length etc
Should it have a label or a placeholder?

It's better to just use a standard ui-bootstrap popover with a custom template and then you have complete control.

**Comment by aurimus** [comment]
I think it could allow a whole form to be in the inner html, then you could have whatever you want

**Comment by mattlewis92** [comment]
In which case you can do that with a custom template, I've just released a new feature that let's you pass values e.g. an input text, to the confirm and cancel outputs. You can see the tests for an example of how to do this: https://github.com/mattlewis92/angular-bootstrap-confirm/blob/master/test/angular-bootstrap-confirm.spec.js#L458
