### ISSUE TITLE
Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by JoseGoncalves** [mattlewis92/angular-bootstrap-confirm#31]
In one of my use cases I've reached a situation where on the '$destroy' event the popover is not created and I get an _Cannot read property 'remove' of undefined_ error. Looking at the HTML I still see a popover div element after this error.
To workaround with this I wrapped the '$destroy' handler with a zero $timeout and then all goes fine.

**Comment by mattlewis92** [comment]
Thanks for reporting, should be fixed in 2.4.1!
