### ISSUE TITLE
Support for animation

### ISSUE THREAD

**Issue by 19majkel94** [mattlewis92/angular-bootstrap-confirm#32]
The original [Angular UI Bootstrap Popover](http://angular-ui.github.io/bootstrap/#/popover) has support for animations by ngAnimate. Is there an option to support it here too? I like the UI popover but it creates new DOM for popover which is out of the scope so can't bind button ng-click to the accurate scope and do the confirm button action in template like in this directive.

**Comment by mattlewis92** [comment]
Thanks for the suggestion, I've added support in 2.5.0! 

p.s. you can actually access the outer scope with ui-bootstrap if using a custom template! 😄

**Comment by 19majkel94** [comment]
Do you know how to use custom template with webpack? For components declaration I use `template: require('template.html')` which inline the html into string.

**Comment by mattlewis92** [comment]
You can use the `$templateCache` for this, see the tests for an example: https://github.com/mattlewis92/angular-bootstrap-confirm/blob/master/test/angular-bootstrap-confirm.spec.js#L448-L454
