### ISSUE TITLE
is open should not be mandatory

### ISSUE THREAD

**Issue by court-jus** [mattlewis92/angular-bootstrap-confirm#6]
If one does not specify the is-open property, there is this error :

```
Error: [$compile:nonassign] Expression 'undefined' used with directive 'mwlConfirm' is non-assignable!

**Comment by mattlewis92** [comment]
That's odd because the demo doesn't use `is-open` and it doesn't have any errors. What version of angular are you using? Can you share a plunker, codepen etc that reproduces your issue. Thanks!

**Comment by court-jus** [comment]
Hi,
I'm using angular 1.3, I'll try to create a plunker

**Comment by court-jus** [comment]
Hmm I don't know how to include dependencies into plunker. I tried like that http://plnkr.co/edit/vgAMPGzpAvbaGA5Ht7My?p=info but it refuses to load your code from github

**Comment by mattlewis92** [comment]
It was an issue with angular 1.3, I've pushed 0.3.1 which will fix it :)

**Comment by court-jus** [comment]
Thanks !
