### ISSUE TITLE
compatibility with TextAngular

### ISSUE THREAD

**Issue by bartes** [mattlewis92/angular-bootstrap-confirm#7]
https://github.com/fraywing/textAngular doesn't allow to have angular-sanitize, it uses textangular-sanitize (with same naming as angualar-sanitize). Can we have angular-sanitize self-includable by user ?

**Comment by mattlewis92** [comment]
Like you said textAngulars fork of ngSanitize is a drop in replacement so just use that instead. ngSanitize isn't bundled with this plugin.

**Comment by bartes** [comment]
but it is marked as dependency in package.json so I'm not sure is there a way to disable that in eg. browserify

**Comment by mattlewis92** [comment]
Ah right I didn't realise you were consuming from npm. You will need to shim the ngSanitize module with the one provided by textAngular, I only have experience with webpack and not browserify but it should be doable using something like: https://github.com/thlorenz/browserify-shim/wiki/browserify-shim-recipes

**Comment by bartes** [comment]
Thnx. So final solution for my case is:
1) set forceTextAngularSanitize: false in textAngular config (which will allow to use angular-sanitize require statement)
2) require('angular-sanitize') instead and require('textangular-sanitize') in the app
3) cheat everybody by pointing    "angular-sanitize": "./node_modules/textAngular/dist/textAngular-sanitize.js in packags.json browser section (for browserify-shim)
