### ISSUE TITLE
bower dependencies

### ISSUE THREAD

**Issue by bastianh** [mattlewis92/angular-bootstrap-confirm#8]
Hi, 

could you please remove bootstrap from bower dependencies? I'm using the official bootstrap-sass bower package, so installing the bootstrap package is not necessary. 
(It's also not required if you use the bootstrap cdn for example, and since it does not really require bootstrap as a javascript dependency I think it's not really needed).

Thanks
  Bastian

**Comment by mattlewis92** [comment]
I'm guessing you're using something like wiredep to auto include your dependencies? If so I'd suggest just using the bower overrides feature to stop bootstrap getting injected into your app. 

I'm going to keep it as a dependency as the majority of people will be using the bootstrap css or less files so it is applicable for those people.

**Comment by bastianh** [comment]
I was just using bower, but did not know the overrides feature. Thanks.
